"""Add lemonsqueezy

Revision ID: f8e555d5e953
Revises: 1fcbba69433f
Create Date: 2025-12-11 14:44:01.967172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e555d5e953'
down_revision = '1fcbba69433f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lemon_squeezy_order_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('lemon_squeezy_order_id')

    # ### end Alembic commands ###
